---
title: "Project Check-in 2"
author: "Charles Zhang, Roan Floer-Martinez, Jinghan Zhou, Xi Feng"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r message=FALSE}
library(readr)
library(tidyverse)
library(lubridate)
library(skimr) 
library(naniar) 
library(ggmap)
library(gplots) 
library(RColorBrewer) 
library(sf) 
library(leaflet)
library(formattable)
library(shiny)
```

## Dataset: Pizza Party

```{r}
# Read Data
pizza_jared <- readr::read_csv("https://raw.githubusercontent.com/RoanFM/Compsci-final/master/Data/pizza_jared.csv") %>% 
  unique() 
pizza_barstool <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_barstool.csv") %>% 
  unique()
pizza_datafiniti <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_datafiniti.csv") %>% 
  unique()
```


### **Pizza in the U.S.**

```{r}
glimpse(pizza_datafiniti)
```
```{r}
leaflet(data=pizza_datafiniti) %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>% 
  addCircleMarkers(lng = ~longitude, lat = ~latitude, color = "red", label=~name,stroke = FALSE, fillOpacity = 0.5, radius = 2)
```


### **Most popular pizza place**

```{r}
pizza_datafiniti %>% 
  group_by(city) %>% 
  summarise(n = n()) %>%
  mutate(city = fct_reorder(city, n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x=city, y=n,fill=city))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  theme(legend.position="none")+
  labs(title = "Top 10 Cities for Pizza") 
```

```{r}
nyc_pizza <- pizza_datafiniti %>% 
  filter(city == "New York")
```

### **Pizza in the NYC**

```{r}
leaflet(data=nyc_pizza) %>% 
  addProviderTiles(providers$Stamen.Toner) %>% 
  addMarkers(lng = ~longitude, lat = ~latitude, label = ~name,clusterOptions = markerClusterOptions())
```

### **Pizza Evaluation**

```{r}
glimpse(pizza_jared)
pizza_jared<-pizza_jared %>% 
  mutate(date = as_datetime(time)) 
glimpse(pizza_jared)
```

```{r}
# sum the total votes and rate
pizza_excellent <- pizza_jared %>% 
  filter(answer=="Excellent") %>% 
  group_by(place) %>% 
  mutate(sum_votes=sum(votes), sum_total=sum(total_votes)) %>% 
  mutate(p = sum_votes/sum_total)

pizza_good <- pizza_jared %>% 
  filter(answer=="Good") %>% 
  group_by(place) %>% 
  mutate(sum_votes=sum(votes), sum_total=sum(total_votes)) %>% 
  mutate(p = sum_votes/sum_total)

pizza_average <- pizza_jared %>% 
  filter(answer=="Average") %>% 
  group_by(place) %>% 
  mutate(sum_votes=sum(votes), sum_total=sum(total_votes)) %>% 
  mutate(p = sum_votes/sum_total)

pizza_poor <- pizza_jared %>% 
  filter(answer=="Poor") %>% 
  group_by(place) %>% 
  mutate(sum_votes=sum(votes), sum_total=sum(total_votes)) %>% 
  mutate(p = sum_votes/sum_total)

pizza_never <- pizza_jared %>% 
  filter(answer=="Never Again") %>% 
  group_by(place) %>% 
  mutate(sum_votes=sum(votes), sum_total=sum(total_votes)) %>% 
  mutate(p = sum_votes/sum_total)

# create pizza rating data frame
pizza_rating <- rbind(pizza_excellent, pizza_good, pizza_average, pizza_poor, pizza_never) %>% 
  mutate(year=year(date)) %>% 
  group_by(place, year, answer) %>% 
  mutate(year_avr_rate = mean(p)) 

glimpse(pizza_rating)
```
```{r}
# Top ten highest Excerllent rate 
top_ten_excellent<-pizza_rating %>% 
  filter(answer=="Excellent") %>% 
  group_by(place) %>% 
  summarise(Excellent = sum(year_avr_rate)/n()) %>% 
  arrange(desc(Excellent)) %>% 
  head(10) 

# Other answers for these ten pizzas
top_exe_good <- top_ten_excellent %>% 
  inner_join(pizza_rating, by="place") %>% 
  filter(answer=="Good") %>% 
  group_by(place) %>% 
  summarise(Good = sum(year_avr_rate)/n()) 

top_exe_avr<- top_ten_excellent %>% 
  inner_join(pizza_rating, by="place") %>% 
  filter(answer=="Average") %>% 
  group_by(place) %>% 
  summarise(Average = sum(year_avr_rate)/n()) 

top_exe_poor<- top_ten_excellent %>% 
  inner_join(pizza_rating, by="place") %>% 
  filter(answer=="Poor") %>% 
  group_by(place) %>% 
  summarise(Poor = sum(year_avr_rate)/n()) 

top_exe_never<- top_ten_excellent %>% 
  inner_join(pizza_rating, by="place") %>% 
  filter(answer=="Never Again") %>% 
  group_by(place) %>% 
  summarise(Never_Again = sum(year_avr_rate)/n())

top_ten_excellent_analysis <- top_ten_excellent %>% 
  inner_join(top_exe_good,by = "place") %>% 
  inner_join(top_exe_avr,by = "place") %>% 
  inner_join(top_exe_poor,by = "place") %>% 
  inner_join(top_exe_never,by = "place") %>% 
  pivot_longer(cols= -place,names_to = "Answers",values_to = "Proportion")
```
```{r, fig.width=8}
# Graph
top_ten_excellent_analysis %>% 
  ggplot(aes(x=place, y=Proportion, fill=Answers))+
  geom_bar(stat='identity')+
  scale_fill_manual("legend", values = c("darkorchid2","dodgerblue2","darkgoldenrod1","cyan3","brown3"))+
  theme_classic()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  xlab("Place")+
  labs(title = "Evaluation for Top 10 Pizza Place")
```

```{r}
glimpse(pizza_barstool)
```

```{r}
city_average_score <- pizza_barstool %>% 
  group_by(city) %>% 
  summarise(city_average_score = sum(review_stats_all_average_score)/n()) 
```


```{r}
pizza_barstool %>% 
  ggplot(aes(x=price_level, y=review_stats_all_average_score))+
  geom_boxplot()
```

